        <div class="item-details">
            <div class="cell">
                <div class="item-picture">
                    <?php echo $this->partial('ololz/p/item/picture-icon', array('item' => $item)) ?>
                </div>
            </div>
            <div class="cell">
               <div class="item-name">
                    <p><?php echo $item->getName() ?></p>
                </div>
            </div>
        </div>
