                    <div class="summoner-invocation-details-gold">
                        <?php if (! is_null($invocation->getGold())) : ?>
                            <p>
                                <?php echo sprintf($this->translate('%d k'), $invocation->getGold()) ?><br />
                                <?php echo $this->translate('Gold') ?>
                            </p>
                        <?php endif; ?>
                    </div>