<?php echo $this->form()->openTag($this->formSearchInvocation()) ?>

<div class="input-daterange">
    <span><?php echo $this->formSearchInvocation('search_invocation')->get('date_min')->getLabel() ?> :</span>
    <?php echo $this->formText()->render($this->formSearchInvocation('search_invocation')->get('date_min')) ?>
    <span><?php echo $this->formSearchInvocation('search_invocation')->get('date_max')->getLabel() ?> : </span>
    <?php echo $this->formText()->render($this->formSearchInvocation('search_invocation')->get('date_max')) ?>
</div>

<div>
    <span><?php echo $this->formSearchInvocation('search_invocation')->get('champion')->getLabel() ?> : </span>
    <?php echo $this->formSelect()->render($this->formSearchInvocation('search_invocation')->get('champion')) ?>
    <span><?php echo $this->formSearchInvocation('search_invocation')->get('position')->getLabel() ?> : </span>
    <?php echo $this->formSelect()->render($this->formSearchInvocation('search_invocation')->get('position')) ?>
</div>
<div>
    <span><?php echo $this->formSearchInvocation('search_invocation')->get('map')->getLabel() ?> : </span>
    <?php echo $this->formSelect()->render($this->formSearchInvocation('search_invocation')->get('map')) ?>
    <span><?php echo $this->formSearchInvocation('search_invocation')->get('match_type')->getLabel() ?> : </span>
    <?php echo $this->formSelect()->render($this->formSearchInvocation('search_invocation')->get('match_type')) ?>
</div>

<div>
    <span><?php echo $this->formSearchInvocation('search_invocation')->get('limit')->getLabel() ?> : </span>
    <?php echo $this->formText()->render($this->formSearchInvocation('search_invocation')->get('limit')) ?>
</div>

<div id="search_actions">
    <?php echo $this->formButton()->render($this->formSearchInvocation()->get('search')) ?>
</div>

<?php echo $this->form()->closeTag($this->formSearchInvocation()) ?>

<script type="text/javascript">
$(function() {
} );
</script>