<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Open LoL Ztatistics'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/ololz.css')
//                        ->prependStylesheet($this->basePath() . '/assets/bootstrap/bootstrap-responsive.css')
//                        ->prependStylesheet($this->basePath() . '/assets/ololz/ololz.css')
//                        ->prependStylesheet($this->basePath() . '/assets/bootstrap/bootstrap.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
                        ->prependFile($this->basePath() . '/assets/ololz/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                        ->prependFile($this->basePath() . '/js/ololz.js')
//                        ->prependFile($this->basePath() . '/assets/ololz/ololz.js')
//                        ->prependFile($this->basePath() . '/assets/bootstrap/bootstrap.js')
//                        ->prependFile($this->basePath() . '/assets/jquery/jquery.js') ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand ololz-color" href="<?php echo $this->url('ololz') ?>"><?php echo $this->translate('oLolz') ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('ololz') ?>"><?php echo $this->translate('Home') ?></a></li>
                            <li><a href="<?php echo $this->url('ololz/summoners') ?>"><?php echo $this->translate('Summoners') ?></a></li>
                            <li><a href="<?php echo $this->url('ololz/matches') ?>"><?php echo $this->translate('Matches') ?></a></li>
                            <li><a href="<?php echo $this->url('ololz/champions') ?>"><?php echo $this->translate('Champions') ?></a></li>
                            <li><a href="<?php echo $this->url('ololz/items') ?>"><?php echo $this->translate('Items') ?></a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p><?php echo $this->translate('Open LoL Ztatistics is an open source software.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
