<div style="float:left; padding-right:16px; width: 150px;">
    <h2>Results</h2>
    <p><?php echo $this->translate((string) $match->getMatchType()) ?></p>
    <p>Played the <?php echo $match->getDate()->format('d/m/Y \a\t H:i') ?></p>
    <p>Last <?php echo $match->getLength() ?> mins</p>
</div>
<div style="margin-left: 160px;">
    <div id="teams">
        <h3>Winners</h3>
        <ul class="nav nav-tabs nav-stacked">
        <?php foreach ($winner->getInvocations() as $invocation) : ?>
            <?php if ($invocation instanceof \Ololz\Entity\Invocation) : ?>
                <?php echo $this->partial('ololz/p/match/invocation', array('summoner' => $invocation->getSummoner(), 'invocation' => $invocation, 'match' => $invocation->getMatchTeam()->getMatch())) ?>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
        <h3>Losers</h3>
        <ul class="nav nav-tabs nav-stacked">
        <?php foreach ($loser->getInvocations() as $invocation) : ?>
            <?php if ($invocation instanceof \Ololz\Entity\Invocation) : ?>
                <?php echo $this->partial('ololz/p/match/invocation', array('summoner' => $invocation->getSummoner(), 'invocation' => $invocation, 'match' => $invocation->getMatchTeam()->getMatch())) ?>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
    </div>
</div>
<div style="clear:both;"></div>
