<div style="float:left; padding-right:16px; width: 150px;">
    <h3>The matches</h3>
</div>
<div style="margin-left: 160px;">
<?php if (count($matches)) : ?>
    <ul class="nav nav-tabs nav-stacked">
        <?php foreach ($matches as $match) : ?>
            <?php if ($match instanceof \Ololz\Entity\Match) : ?>
                <li><a href="<?php echo $this->url('ololz/match', array('match' => $match->getId()))?>"><?php echo $match ?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
</div>
<div style="clear:both;"></div>
