
                <?php foreach ($matches as $match) : ?>
                    <?php if ($match instanceof \Ololz\Entity\Match) : ?>
                    <li>
                        <a href="<?php echo $this->url('ololz/match', array('match' => $match->getId()))?>">
                            <?php echo $this->partial('ololz/p/match/line', array('match' => $match)) ?>
                        </a>
                    </li>
                    <?php endif; ?>
                <?php endforeach; ?>