        <li>
            <a class="<?= $invocation->getMatchTeam()->hasWon() ? 'win' : 'loss' ?>" href="<?php echo $this->url('ololz/summoner', array('summoner' => $summoner->getId()))?>">
                <?php echo $this->partial('ololz/p/invocation/line', array(
                        'details' => array('champion', 'summoner', 'kda', 'gold', 'minions', 'spells', 'items'),
                        'summoner' => $summoner,
                        'invocation' => $invocation,
                        'match' => $match
                ) ) ?>
            </a>
        </li>
