<div class="hero-unit">
    <h1><?php echo sprintf($this->translate('Welcome to %sOpen LoL Ztatistics%s'), '<span class="ololz-color">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sOpen LoL Ztatistics%s. You are currently running oLolz version %s.'), '<a href="https://github.com/olol/ololz" target="_blank">', '</a>', '0.1.0') ?></p>
    <p><a class="btn btn-success btn-large" href="https://github.com/olol/ololz/wiki/Get-matches-data-of-a-summoner" target="_blank"><?php echo $this->translate('Learn how to add summoners') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="span6">
        <h2><?php echo $this->translate('Just the beginning') ?></h2>
        <p><?php echo sprintf($this->translate('Once you have %sadded one or more summoners%s into the database and %sretrieved matches data%s, you will be able to see a list of thoses matches by clicking "%sMatches%s" in the top menu.'), '<a href="https://github.com/olol/ololz/wiki/Get-matches-data-of-a-summoner#add-the-summoner-into-ololz" target="_blank">', '</a>', '<a href="https://github.com/olol/ololz/wiki/Get-matches-data-of-a-summoner#retrieve-matches-data-from-lol-king" target="_blank">', '</a>', '<a href="' . $this->url('ololz/matches')  . '">', '</a>') ?></p>
        <p><?php echo sprintf($this->translate('You will also be able %sto list those summoners%s and get more detailed data about them on there specific pages.'), '<a href="' . $this->url('ololz/summoners')  . '">', '</a>') ?></p>
        <p><?php echo sprintf($this->translate('Sounds not like a lot ? Yeah you are right ! But more is coming soon, promise !')) ?></p>
        <p><a class="btn btn-success" href="https://github.com/olol/ololz" target="_blank"><?php echo $this->translate('Follow oLolz development') ?> &raquo;</a></p>
    </div>

    <div class="span6">
        <h2><?php echo $this->translate('Wanna be part of it ?') ?></h2>
        <p><?php echo sprintf($this->translate('oLolz is an open source software, thus meaning that any one can participate, no matter what his skills are. We just need good will as there is plenty of stuff to do (you bet!).')) ?></p>
        <p><?php echo sprintf($this->translate('Do you have any ideas of some cool stats we could add ? Do you speak a language not supported yet ? Maybe you think our design sucks and you can give us a hand there ? Or you know some PHP coding ?')) ?></p>
        <p><a class="btn btn-success" href="https://github.com/olol/ololz" target="_blank"><?php echo $this->translate('Get your hands dirty') ?> &raquo;</a></p>
   </div>
</div>
