<div style="float:left; padding-right:16px; width: 150px;">
    <h3>The champions</h3>
</div>
<div style="margin-left: 160px;">
<?php if (count($champions)) : ?>
    <ul class="nav nav-tabs nav-stacked">
        <?php foreach ($champions as $champion) : ?>
            <?php if ($champion instanceof \Ololz\Entity\Champion) : ?>
                <li><a href="<?php echo $this->url('ololz/champion', array('champion' => $champion->getCode()))?>"><img src="<?php echo $this->championPictureUrl($champion)?>" alt="champion icon" /> <?php echo $champion->getName() ?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
</div>
<div style="clear:both;"></div>
