        <div class="champion-details">
            <div class="cell">
                <div class="champion-picture">
                    <?php echo $this->partial('ololz/p/champion/picture-small', array('champion' => $champion)) ?>
                </div>
            </div>
            <div class="cell">
                <div class="champion-name">
                    <p><?php echo $champion->getName() ?></p>
                </div>
            </div>
        </div>
